### ISSUE TITLE
No visual distinction between kogia.herokuapp.com/fundcreate and kogia.herokuapp.com/borrowcreate

### ISSUE THREAD

**Issue by guybrushT54** [ETHLend/Kogia#10]
it s not easy to understand in wich section we are.

**Comment by shaneBen23** [comment]
Hi, thank you for pointing that out. We will work on making these 2 pages more distinct in there appearance.

**Comment by shaneBen23** [comment]
Derien! :)

**Comment by vvville** [comment]
@guybrushT54 Can you contact ETHLend through either Gitter or Telegram about the Bug Bounty? Thanks!
