### ISSUE TITLE
Frozen loan request

### ISSUE THREAD

**Issue by Kenosaurus** [ETHLend/Kogia#103]
When creating a new loan request using LEND as medium, it got stuck here and never produced the "fund" box. I tried reversing one step and then it "froze" and kept loading the page (loading circle)...

Also can we add after premium what currency it is in?

<img width="1087" alt="nayttokuva 2018-04-11 kello 18 24 55" src="https://user-images.githubusercontent.com/22507601/38627265-43c12fec-3db7-11e8-9624-3e351b307327.png">

**Comment by FooLoor** [comment]
Having the same issue.

![image](https://user-images.githubusercontent.com/38444295/38839634-3d80bb32-41a1-11e8-9635-69372c075e78.png)
