### ISSUE TITLE
loan request for LEND

### ISSUE THREAD

**Issue by pnielab** [ETHLend/Kogia#12]
![1](https://user-images.githubusercontent.com/7129778/38396768-769d9190-3942-11e8-9417-5046c720ceb6.PNG)

create a loan resuest with LEND chrome browser

tooltipe is disabled.
installment period indays max 10 days.
collateral amount is wrong.

**Comment by shaneBen23** [comment]
Hi, we are aware of this issue. And we will be deploying the correction in our next update.
