### ISSUE TITLE
user experience scroll down bar confusing

### ISSUE THREAD

**Issue by pnielab** [ETHLend/Kogia#13]
go to all offers tab
there is a difference between the 2 scroll bars, the one in the filter section is small and difficult to see, both scrollbars should be with the same size and should behave the same, the big one has on hoover event while the filter scrollbar do not react.
using chrome
![2](https://user-images.githubusercontent.com/7129778/38396973-c3aa38de-3943-11e8-9b48-99488ef38156.PNG)

**Comment by shaneBen23** [comment]
Hi @pnielab,
I understand, we will work on synchronising these 2 scrollbars in a more user friendly way. 
Thanks.
