### ISSUE TITLE
back button is missing

### ISSUE THREAD

**Issue by pnielab** [ETHLend/Kogia#14]
using chrome.
go to all offres tab.
pres on one of the loans.
you can not go back you need to press all offers tab again. maybe open a popup instead of navigating loading another page.. this way you can close the popup and see all the loans exactly in the scrollbar... where you located in your search
![3](https://user-images.githubusercontent.com/7129778/38397283-88e2ed16-3945-11e8-8f48-5fdc6929c9eb.PNG)

**Comment by shaneBen23** [comment]
Hi @pnielab,
We will see how we can get this done in development else we will find another way to make the viewing experience easier. 
Thanks!
