### ISSUE TITLE
No difference between nightmode On and Off 

### ISSUE THREAD

**Issue by sirsoth** [ETHLend/Kogia#15]
There's no difference when I change between nightmode, also when I change that option and I refresh the browser my option doesnt mantain (If I chose nightmode off when I refresh is on now)

System: 
Windows 10 64 bits
Chrome 65.0.3325.181 64 bits

**Comment by shaneBen23** [comment]
Hi @sirsoth,
This functionality has not been added with this release. It will me added in the Mainnet version.
