### ISSUE TITLE
bug when creating a new borrow request

### ISSUE THREAD

**Issue by pnielab** [ETHLend/Kogia#16]
go to the menu in the upper left side and select Borrow.
select eth lend collateral and press create.
methamask popup and the ui represent a sandbox for loading.
close metamask, ui need to stop sandbox, instead,
![4](https://user-images.githubusercontent.com/7129778/38397508-a7d98012-3946-11e8-9563-9d7cb63d402e.PNG)
 it hangs for a lot of time

**Comment by shaneBen23** [comment]
Hi @pnielab,
It is not the application that is lagging, the application is waiting for a response from the blockchain and this process could take some time.
