### ISSUE TITLE
Lend exception page

### ISSUE THREAD

**Issue by RamjeeSingh** [ETHLend/Kogia#18]
Please check this exception page. This was random steps clicking here and their.

The call is from "The call is from " return instanceLoanOffersLedgerContract.methods.getLendingContractsCount().call({ from: _this.props.userData.currentUserAddress });" what if the person who is browsing the application does not have contract address...will it throw such page to user who is browsing the website"

![lendexception](https://user-images.githubusercontent.com/25591618/38404522-5253ecee-3988-11e8-8c4f-11ad73bde7ff.png)
![lendexception1](https://user-images.githubusercontent.com/25591618/38404543-6ce4f2ce-3988-11e8-9722-bf2d9dbe66c5.png)

**Comment by shaneBen23** [comment]
Hi @RamjeeSingh,
This is only a test version of the application. What you are seeing is a client side error. This will not be in the final release of the application.
Thanks.

**Comment by vvville** [comment]
@RamjeeSingh Can you contact ETHLend through Telegram or Gitter about Bug Bounty? Thanks!

**Comment by RamjeeSingh** [comment]
Hi Ville,

Thanks for contacting me. I am not able to get in touch with you on telegram( Telegram ID @**rockrama**).

Please let me know what steps to claim bug bounty.

Regards,
Ramjee Singh

**Comment by vvville** [comment]
Hi,

Can you send me your ETH wallet address and I will handle the rest for the distribution! 

Best Regards,
Ville


Lähettäjä: RamjeeSingh
Lähetetty: tiistai 3. heinäkuuta 2018 11.50
Vastaanottaja: ETHLend/Kogia
Kopio: Ville Valkonen; State change
Aihe: Re: [ETHLend/Kogia] Lend exception page (#18)

Hi Ville,
Thanks for contacting me. I am not able to get in touch with you on telegram( Telegram ID @rockrama).
Please let me know what steps to claim bug bounty.
Regards,
Ramjee Singh
