### ISSUE TITLE
Lend Tutorial screen posts same set of videos

### ISSUE THREAD

**Issue by RamjeeSingh** [ETHLend/Kogia#19]
So many videos attached in this screen http://kogia.herokuapp.com/tutorials its confusing for end user and user can watch all videos
![lendtutorial](https://user-images.githubusercontent.com/25591618/38404673-6dddfe04-3989-11e8-91b6-deceee8fc0e8.png)

**Comment by shaneBen23** [comment]
Hi @RamjeeSingh,
This is a display page for show purposes. It will be up to date in the final release.
Thanks.
