### ISSUE TITLE
when i click lend it takes me to the borrow screen 

### ISSUE THREAD

**Issue by birdman718** [ETHLend/Kogia#2]
when i click lend it takes me to the borrow screen in the beginning

**Comment by birdman718** [comment]
It is not allowing me to lend from the beginning screen

**Comment by birdman718** [comment]
0x6a7214c0f265fbfe0e7c59a9b44981c8ec7fb94a

**Comment by guybrushT54** [comment]
me too

**Comment by shaneBen23** [comment]
Hi, @guybrushT54 is right. If you would like to fund a loan. You should go to the all loans screen.
