### ISSUE TITLE
Faq has same answer for all question and not easily understandable 

### ISSUE THREAD

**Issue by RamjeeSingh** [ETHLend/Kogia#20]
http://kogia.herokuapp.com/faq has same answers preloaded for all questions.
![faq_screen](https://user-images.githubusercontent.com/25591618/38404728-bff93d3e-3989-11e8-924d-2c026655264b.png)

**Comment by shaneBen23** [comment]
Hi @RamjeeSingh,
This is a display page for show purposes. It will be up to date in the final release.
Thanks.
