### ISSUE TITLE
no preview for night mode on/off

### ISSUE THREAD

**Issue by RamjeeSingh** [ETHLend/Kogia#22]
Preview/background not change for user feel when night mode is on or off PFA for on and off
![on](https://user-images.githubusercontent.com/25591618/38405592-4263a80a-398e-11e8-87de-1bf1ff833f22.png)
![mode_off](https://user-images.githubusercontent.com/25591618/38405610-543809e0-398e-11e8-9a59-9c047db28da5.png)

**Comment by shaneBen23** [comment]
This is a duplication. see No difference between nightmode On and Off #15
