### ISSUE TITLE
total loan period is wrong

### ISSUE THREAD

**Issue by pnielab** [ETHLend/Kogia#23]
Using chrome,
go to create a new lend request, choose 2 installment and 10 days period, now go and press collateral amount token unit button and see that the total amount changes from 20 to 30
total loan period should be 20 but it shows 30

**Comment by pnielab** [comment]
![5](https://user-images.githubusercontent.com/7129778/38411464-ca4acdba-398f-11e8-9078-7919c236ba5c.PNG)

**Comment by shaneBen23** [comment]
Hi @pnielab,
We have already addressed this issue here. the loan request for LEND #12
