### ISSUE TITLE
missing button to proceed to send tokens

### ISSUE THREAD

**Issue by pnielab** [ETHLend/Kogia#24]
![6](https://user-images.githubusercontent.com/7129778/38411365-9be7a218-398f-11e8-90f5-457e89d55931.PNG)

create a loan request with lend tokens. you can not proceed after entering all parameters, no button.
using chrome

**Comment by shaneBen23** [comment]
Hi @pnielab,
In this section the page does a check on the blockchain before. Displaying the button, this may take some time but the button will appear.

**Comment by vvville** [comment]
@pnielab Can you contact ETHLend through either Telegram or Gitter for Bug Bounty? Thanks!
