### ISSUE TITLE
Empty loans are shown under View All Loans

### ISSUE THREAD

**Issue by nikes90** [ETHLend/Kogia#34]
Hi,

When I click on "View All Loans" it shows loans with no details [No Data].
Either the loan details are not loading due to a bug or the view shows empty loans !
![screenshot from 2018-04-07 09 54 53](https://user-images.githubusercontent.com/6938404/38451233-04928b2e-3a4a-11e8-8996-76037d3890c8.png)

**Comment by shaneBen23** [comment]
Hi @nikes90,
They are not empty. The data has not yet been set by the lender.
