### ISSUE TITLE
[Set Data] field shows all empty loans with [No Data]

### ISSUE THREAD

**Issue by nikes90** [ETHLend/Kogia#35]
Hi, 

When I go to "View All Loans" and go to Filter Loans - and click on "Loan State" 
When only "Set Data" field is selected only shows empty loans!!
![screenshot from 2018-04-07 10 02 22](https://user-images.githubusercontent.com/6938404/38451275-ca7833a2-3a4a-11e8-9257-2150f34d8a24.png)

**Comment by shaneBen23** [comment]
Duplication Empty loans are shown under View All Loans #34
