### ISSUE TITLE
NIGHT MODE does not work

### ISSUE THREAD

**Issue by nikes90** [ETHLend/Kogia#36]
Hi,

Night mode does not work !

When I turn NightMode On/Off I do not see any change.
![screenshot from 2018-04-07 10 39 36](https://user-images.githubusercontent.com/6938404/38451574-03c42ad0-3a50-11e8-9494-0c32c71e140c.png)
![screenshot from 2018-04-07 10 39 31](https://user-images.githubusercontent.com/6938404/38451575-03f5caa4-3a50-11e8-9417-1fadbd33dcaa.png)

**Comment by shaneBen23** [comment]
This is a duplication. of issue #15
