### ISSUE TITLE
Loan To Value help not working

### ISSUE THREAD

**Issue by nikes90** [ETHLend/Kogia#37]
Hi,

Loan to Value help (?) not working.

When I click on (?) right next to Loan to Value in below screen, no info is shown.
![screenshot from 2018-04-07 10 50 03](https://user-images.githubusercontent.com/6938404/38451650-9f16fd22-3a51-11e8-901e-d4cd90492358.png)

**Comment by shaneBen23** [comment]
This is a duplication of this issue #3
