### ISSUE TITLE
About page has link to CMC missing

### ISSUE THREAD

**Issue by nikes90** [ETHLend/Kogia#45]
Hello,

About page [https://kogia.herokuapp.com/about] has link to coinmarketcap missing. I see only text [LINK TO CMC] but no href link :(
![screenshot from 2018-04-07 20 29 40](https://user-images.githubusercontent.com/6938404/38456469-9f090464-3aa2-11e8-8532-0fa3d7958dcb.png)

**Comment by shaneBen23** [comment]
Hi @nikes90,
That is the link added by the widget not us. If it doesn't work it has something to do with CMC not us.
Sorry.
