### ISSUE TITLE
About page price chart is misleading 

### ISSUE THREAD

**Issue by nikes90** [ETHLend/Kogia#46]
Hi,

About page - https://kogia.herokuapp.com/about price chart is misleading, there is not mention of units
![screenshot from 2018-04-07 20 29 40](https://user-images.githubusercontent.com/6938404/38456503-de8b86de-3aa2-11e8-9889-5c96cd9f2642.png)

**Comment by shaneBen23** [comment]
Hi @nikes90,
This cart is for display purposes it is not an accurate representation of the price of LEND.
