### ISSUE TITLE
Clicking the button does not work unless you click the word on it. 

### ISSUE THREAD

**Issue by xiaohang007** [ETHLend/Kogia#48]
For example: If I would like to borrow, I need to precisely click on the "Borrow" word, which is kind of inconvenient. If I click the shadowed region shown in the figure below, it does not work, which should be fixed in my opinion. 
![capture](https://user-images.githubusercontent.com/33337564/38461446-48ac8eaa-3a9e-11e8-9b5d-aef60210f4f4.PNG)

**Comment by shaneBen23** [comment]
Hi @xiaohang007,
we will work on making the whole section clickable. thank you.

**Comment by xiaohang007** [comment]
Good for LEND! Thank you!
