### ISSUE TITLE
Taking Too Long To Load on Chrome

### ISSUE THREAD

**Issue by nyankomo** [ETHLend/Kogia#49]
Hello 

I am trying to create a loan on KOIGA but it is taking too long to load. There is two circles which keep rotating forever. Any solution.

**Comment by quinnk31** [comment]
I have this same problem. After checking it in the chrome developer tools, I see the following attached message in the query to coinmarketcap.com. I suspect it may be the culprit in many of the bugs reported.

"Please enable cookies.
Error 1015 Ray ID: 408571957cf699e6 • 2018-04-08 14:32:30 UTC
You are being rate limited
What happened?
The owner of this website (api.coinmarketcap.com) has banned you temporarily from accessing this website.

Cloudfare"
![image](https://user-images.githubusercontent.com/1779457/38468777-bb1d1e30-3b18-11e8-9e16-39805ccf1d71.png)

**Comment by shaneBen23** [comment]
Hi,
Thank you for pointing this out. It seems to be a slow down on the coinmarketcap API. We will see about bring up the number of requests we can make. Or finding a way to work around it.
Thanks
