### ISSUE TITLE
Collateral precision needs adjustment

### ISSUE THREAD

**Issue by quinnk31** [ETHLend/Kogia#50]
I don't think the slider for the collateral amount is usable. For example when I slide it, it goes from 312.50 to 334.83. I cannot select the precise amount of tokens that I have for collateral. 

Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by shaneBen23** [comment]
hi @quinnk31,
We will work on making the sliders have more precision. Or we will put an alternative in place to make this process easier.
Thank you.
