### ISSUE TITLE
Chrome crashed while I was trying to filter loans

### ISSUE THREAD

**Issue by quinnk31** [ETHLend/Kogia#51]
I was setting filters (after clicking "view all offers"), with the following parameters when it happened. Chrome crashed three times so it should be easy to recreate. I set these  parameters each time but I was modifying a different form input each time. The attached screenshot is the view I saw before the second crash and I believe it was about the same for each crash. I believe the LTV was loading for one of the offers presented and may have been indicative of the problem.

collateral type: LEND
currency: LEND
LTV: 80%
Interest Rate: not selected
Loan Period: 100 days
Loan Amount: 20 ETH

![image](https://user-images.githubusercontent.com/1779457/38468596-aa9c777e-3b16-11e8-84e1-480ad95d1478.png)

**Comment by shaneBen23** [comment]
Hi @quinnk31,
We were unable to reproduce your error.
