### ISSUE TITLE
loading take long time+ no access to "my loans"

### ISSUE THREAD

**Issue by Kant19** [ETHLend/Kogia#58]
Hey ethlend team,

I have noticed two problems : 

       1-It takes a long time to load each page, I'm on windows 10 + google chrome, I don't know if it's my connexion (i've tried with my own wi-fi + 4G but nothing)

      2-I can't have access to "my loans"

Thank you

**Comment by shaneBen23** [comment]
Hi @Kant19,
Retrieving data from the blockchain is very time consuming. We can not do anything about the time it takes to load the page.
