### ISSUE TITLE
View All offers / no filter on GET LOAN

### ISSUE THREAD

**Issue by guybrushT54** [ETHLend/Kogia#7]
<img width="1384" alt="screen shot 2018-04-05 at 23 37 45" src="https://user-images.githubusercontent.com/38115816/38393250-914e01f4-392a-11e8-94d2-10929f40032a.png">

**Comment by shaneBen23** [comment]
Hi, the filter function has not been completed yet. It is there for display purposes. This will be added in the mainnet release.
