### ISSUE TITLE
In case of borrower not claiming the funds

### ISSUE THREAD

**Issue by h0man** [ETHLend/Kogia#78]
Lender's don't have the possibility to cancel their funding if the borrower never claim fund.

Should he be able to cancel ? Should we put a time limit for the borrower to claim fund, past which the fund will return to the lender ?

**Comment by jchittoda** [comment]
Fixed.
We are going to give Borrower 72 hour period to accept the loan amount.
So when loan is 100% Funded by the Lenders, then within 72 hours Borrower can accept the loan and collect the funds. If he doesn't do that then funds can be claimed back by the Lenders.
