### ISSUE TITLE
Now or on next release: Add check method to check if 100% funded

### ISSUE THREAD

**Issue by LendWarrior** [ETHLend/Kogia#79]
Currently borrower needs to claim funds.

Instead, upon each funding function call we could check IF loan balance + amount the lender is sending equals 100% of the loan amount --> send all balance to borrower.

**Comment by jchittoda** [comment]
Opened an issue, to fix in this release.

**Comment by jchittoda** [comment]
Fixed.
As per the conversation. We are going to give Borrower 72 hour period to accept the loan amount.
So when loan is 100% Funded by the Lenders, then within 72 hours Borrower can accept the loan and collect the funds. If he doesn't do that then funds can be claimed back by the Lenders.
