### ISSUE TITLE
View all offers / Waiting for medium

### ISSUE THREAD

**Issue by guybrushT54** [ETHLend/Kogia#8]
I have create a loan request but I have n t fund.
Then he is listing on the section, but how can I finish the process so someone can GET THe LOAN ?

<img width="500" alt="screen shot 2018-04-05 at 23 42 27" src="https://user-images.githubusercontent.com/38115816/38393838-741fcd18-392c-11e8-8a28-603a69bc4a0e.png">

**Comment by shaneBen23** [comment]
Hi @guybrushT54, 
for you to add the medium to your loan you have to go back to your "my loans" page click on the loan you want to add the medium to and click continue. And from that page you will be able to add the medium.
